---
language: c

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install ruby-full

install:
  - sudo gem install funit

script:
  - make test
  - bin/fetch-configlet
  - bin/configlet .

sudo: required
